version: "3"

services: 
  backend:
    image: ghcr.io/bme-sbt/sbt_backend:brw-toolchain

    ports:
      - 8080:8080
    
    depends_on: 
      - mysql
    
     volumes: 
      - volume_assets:/var/www/html

    restart: unless-stopped

  mysql:
    image: mariadb:10.5.12

    ports:
      - 3306:3306

    environment: 
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpass

    volumes: 
      - volume_mysql:/var/lib/mysql
    
  frontend:
    image: ghcr.io/bme-sbt/sbt_frontend:brw-toolchain

    volumes: 
      - volume_assets:/var/www/html
      - ./cert:/etc/letsencrypt/live/solarboatteam.hu:ro

    ports: 
      - 80:80
      - 443:443

    depends_on: 
      - backend

