version: "3"

services: 
  backend:
    image: ghcr.io/bme-sbt/sbt_backend:brw-toolchain

    ports:
      - 8080:8080
    
    depends_on: 
      - mysql

    restart: unless-stopped

  mysql:
    image: mariadb:10.5.12

    ports:
      - 3306:3306

    environment: 
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpass

    volumes: 
      - ./data/volume_mysql:/var/lib/mysql
    
  frontend:
    image: ghcr.io/bme-sbt/sbt_frontend:brw-toolchain

    ports: 
      - 80:80

    depends_on: 
      - backend

